(ql:quickload :xembed)
(load-module "stumptray")

(setf *window-format* "%m%n%s%c")
(setf *screen-mode-line-format* (list "[^B%n^b] %W^>%d"))
(setf *time-modeline-string* "%a %b %e %k:%M")
(setf *mode-line-timeout* 2)
(setf *mode-line-background-color* *color0*)
(setf *mode-line-foreground-color* *color7*)
(enable-mode-line (current-screen) (current-head) t)
